### ISSUE TITLE
METIS and ParMETIS libraries should be included in pkg-config file

### ISSUE THREAD

**Issue by balos1** [xiaoyeli/superlu_dist#118]
They should be added [here](https://github.com/xiaoyeli/superlu_dist/blob/4fe14ba02cfedb7d60cfcdc8d7a6cb221010d3db/superlu_dist.pc.in#L11) like BLAS so that they are available for linking to static libraries.

**Comment by xiaoyeli** [comment]
I don't fully understand how the pkg-config file is used.
But the difference from BLAS is that: (Par)METIS is not a required library (although highly recommended), while BLAS is required.  That's why only BLAS is listed there.

**Comment by balos1** [comment]
@xiaoyeli (Par)METIS may be optional but once you build SuperLU DIST with it, the produced and installed library does require it. The point of the pc file is to act as a manifest for the installed binary, so it should have (Par)METIS if it was built with it enabled.

**Comment by xiaoyeli** [comment]
There are several other optional libraries: colamd/lapack/CombBLAS, see this configure header file:
https://github.com/xiaoyeli/superlu_dist/blob/master/SRC/superlu_dist_config.h.in

Shall I add all of them?

**Comment by balos1** [comment]
Yes, adding all of them (when they were enabled for the build) would be useful.

**Comment by xiaoyeli** [comment]
added.
