### ISSUE TITLE
Hang during parallel solve after #117

### ISSUE THREAD

**Issue by sebastiangrimberg** [xiaoyeli/superlu_dist#119]
After pulling v8.1.1 I noticed that for certain numbers of processors, SuperLU_DIST hangs during the solve phase occasionally. It does not always happen at the same place, but if I repeatedly solve a system in a loop then it will eventually hang freeze up after a few successful solves. This issue appears after the merge of #117, and reverting the changes in #117 fixes the issue.

Judging by this comment https://github.com/xiaoyeli/superlu_dist/pull/117#pullrequestreview-1109766532, it seems like maybe this was anticipated and just wanted to raise awareness that it certainly does show up for users! Thanks so much.

Sebastian

**Comment by xiaoyeli** [comment]
@jjepson2 @liuyangzhuan 
Seems just changing mpi_test to mpi_wait can cause deadlock.

**Comment by liuyangzhuan** [comment]
Unfortunately, the deadlock seems to be MPI implementation dependent. I think we should still use mpi_test by default, if people encounters deadlocks (such as @jjepson2 's machine), they can switch to mpi_wait?

**Comment by sebastiangrimberg** [comment]
If it helps, I was experiencing the deadlock with OpenMPI 4.1.4 (built with GCC 11).

**Comment by liuyangzhuan** [comment]
@jjepson2 @sebastiangrimberg I forgot to mention that I made this change:
https://github.com/xiaoyeli/superlu_dist/commit/bbc863a2c8f828e747c4df1c56cde374ab26e8ab
So now one can use an env COMM_TREE_MPI_WAIT to control whether MPI_Test (by default) or MPI_Wait is used. 

I'm closing this issue now.
