### ISSUE TITLE
Version 5.2.1, creating make.inc, running make fails, superlu_dist_config.h not created

### ISSUE THREAD

**Issue by zerothi** [xiaoyeli/superlu_dist#13]
I am not sure if the previous issue (#12) is visible, but the issue remains. The target now exists, but they are created in the wrong order, i.e. INSTALL target is runned first.

**Comment by xiaoyeli** [comment]
I am on travel, will take care of it next week.   -Sherry

**Comment by zerothi** [comment]
Sorry for pushing this, I was just unsure about the other issue tracker.

Thanks!

**Comment by xiaoyeli** [comment]
I just updated to v5.2.2, which should have resolved this issue.

**Comment by zerothi** [comment]
Thanks! It works!
