### ISSUE TITLE
Run 'mpirun -np 1 pddrive big.rua', why cost 13s, What could be the reason?

### ISSUE THREAD

**Issue by zhuyidong-YP** [xiaoyeli/superlu_dist#135]
superLU-dist:
FACTOR time 12.342s
SOLVER time 0.143s

While superlu cost very few(0.00855s), i run 'dlinsol < big.rua'.

**Comment by xiaoyeli** [comment]
Something wrong. Please check the following:
1) number of nonzeros in the L and U factors
2) optimizations are on?

**Comment by zhuyidong-YP** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zhuyidong-YP** [comment]
> Something wrong. Please check the following:
> 
> 1. number of nonzeros in the L and U factors
> 2. optimizations are on?

Thanks, i will check it.
It is superLU-Dist EXAMPLE sample 'pddrive', no change on it.I just run it with big.rua file.

superLU-Dist
nonzeros in L 126316
nonzeros in U 126316
nonzeros in L+U 247672

FACTOR time 12.316

superlu
nonzeros in L 27277
nonzeros in U 27277
nonzeros in L+U 49594

FACTOR time 0.00758

**Comment by zhuyidong-YP** [comment]
> Something wrong. Please check the following:
> 
> 1. number of nonzeros in the L and U factors
> 2. optimizations are on?

On other compute, it cost 0.033s. Maybe other cause, Thanks again.
