### ISSUE TITLE
Potential memory problem in superlu_dist

### ISSUE THREAD

**Issue by jjepson2** [xiaoyeli/superlu_dist#148]
Hi,

So I am having a problem with using the COMM_TREE_MPI_WAIT environment variable.  The program dies on line 85 of comm_tree.c on the mpi_wait statement (when using the open source mpich as the implementation).  The mpich people looked at the error logs for the libfabric network, and they said it looks like it could be a memory error to them.  Is it possible that &tree->sendRequests_[idxRecv] is deallocated before the mpi_wait?? (And maybe, before the mpi_isend)

Thanks,
Joseph

**Comment by xiaoyeli** [comment]
@liuyangzhuan Can you please take a look at this? Thanks.

**Comment by liuyangzhuan** [comment]
Ok. It might be due to that if you set COMM_TREE_MPI_WAIT=1, there will be a MPI_Wait call right after each MPI_Isend, but later MPI_Wait is called again in C_BcTree_waitSendRequest and C_RdTree_waitSendRequest, on empty requests. Could you try to comment out the MPI_Wait in C_BcTree_waitSendRequest and C_RdTree_waitSendRequest and see if that fixes the problem? If so, I can commit a bug fix quickly.

**Comment by jjepson2** [comment]
@liuyangzhuan I don't think that your suggestion is the problem, as every mpi_isend should be followed by the mpi_wait under  COMM_TREE_MPI_WAIT.  That's where it is freezing, not on the mpi_wait that is in the other functions (C_BcTree_waitSendRequest and C_RdTree_waitSendRequest ).  Also, in theory mpi_wait should be able to allow a null or inactive request variable.  It's only if the trees themselves are being deallocated before the mpi_wait, that there should be a problem.  

This problem is still mysterious to me, so I'm not completely sure on what actually is going on.  Just that it crashes on that line consistently in superlu_dist.  (line 85)

**Comment by jjepson2** [comment]
The mpich person clarified that the memory problem is occurring when the (later) mpi receiving process tries to read the memory.  So it could be an incorrect size of the read, or it could be the buffer has been deallocated before then.  However, having all the mpi_waits after the mpi_isends should prevent the buffer from being touched before the mpi_receive is complete.  So assuming there isn't some weird memory problem somewhere else, maybe one of the mpi_receive's is wrong?

**Comment by jjepson2** [comment]
In other words, how does it know when it has received a "bad address"?

**Comment by jjepson2** [comment]
I can definitely try that if you would like me to.  However, if you aren't using mpi_irecv, the receive buffer should be safe to use after returning from mpi_recv.  And I notice that anytime you do use mpi_irecv, you are calling the mpi_waitall right after those, so those seem like they should be ok too.

The problem, according to the mpich people, is that when the receiving process tries to read the buffer of the sending process, it causes libfabric to throw a "bad address" error.  I am still waiting for clarification on how mpich determines that it is reading a bad address.  Of course, probably reading unallocated memory could cause that.  And maybe if the count parameter of mpi_recv (or of mpi_isend) is off, maybe that causes it?

**Comment by jjepson2** [comment]
But the mpi_waits after all the mpi_isends should prevent the send buffer from being touched till it is finished.  So maybe the count parameters of either the mpi_isend's or the mpi_recv's is off??

**Comment by liuyangzhuan** [comment]
I don't think the count in MPI_RECV can go wrong. I suggest you give my suggested fix a try since it's a quick change.

**Comment by liuyangzhuan** [comment]
@jjepson2 any follow-up on this?

**Comment by jjepson2** [comment]
Still debugging.  The thing that looked like a memory error might have just been that mpich itself is not fully debugged on NERSC.  (cray-mpich has less problems, but still a hanging problem which I am trying to diagnose).

**Comment by jjepson2** [comment]
So I think it is just a problem with open source mpich (rather than with superlu_dist).  We were able to diagnose the errors we were seeing using cray-mpich, and it was simply us running out of memory on the node because of a memory leak in a wrapper we were using for hdf5 .  For some reason it hung when the memory ran out, rather than giving on OOM memory error, but now we have no hanging problems with cray-mpich.  

So superlu_dist I think should still be good (as long as cray-mpich is being used).  

Thanks for the follow up on this. I'll close it.

**Comment by liuyangzhuan** [comment]
Thanks for figuring this out!
