### ISSUE TITLE
Attempts to build parmetis support when parmetis disabled

### ISSUE THREAD

**Issue by RizzerOnGitHub** [xiaoyeli/superlu_dist#15]
I'm trying to build with parmetis support disabled with -Denable_parmetislib=OFF, for a system where parmetis is not installed (scotch is available instead):

> $ mkdir cmake-build; cd cmake-build
> $ cmake .. -DUSE_XSDK_DEFAULTS=TRUE -DCMAKE_C_COMPILER=mpicc -Denable_parmetislib=OFF

But the build still tries to access parmetis:

>$ make
>Scanning dependencies of target superlu_dist
>[  1%] Building C object SRC/CMakeFiles/superlu_dist.dir/sp_ienv.c.o
>...
>[  9%] Building C object SRC/CMakeFiles/superlu_dist.dir/psymbfact_util.c.o
>[ 10%] Building C object SRC/CMakeFiles/superlu_dist.dir/get_perm_c_parmetis.c.o
>/home/drew/projects/superlu/build/superlu-dist/SRC/get_perm_c_parmetis.c:27:10: fatal error: >parmetis.h: No such file or directory
> #include "parmetis.h"
>          ^~~~~~~~~~~~
>compilation terminated.
>SRC/CMakeFiles/superlu_dist.dir/build.make:398: recipe for target 'SRC/CMakeFiles/superlu_dist.dir/get_perm_c_parmetis.c.o' failed
>make[2]: *** [SRC/CMakeFiles/superlu_dist.dir/get_perm_c_parmetis.c.o] Error 1
>CMakeFiles/Makefile2:981: recipe for target 'SRC/CMakeFiles/superlu_dist.dir/all' failed

If parmetislib is disabled then the build of get_perm_c_parmetis.c should also be disabled.

**Comment by RizzerOnGitHub** [comment]
Probably get_perm_c_parmetis.c should still be built, but placed inside an #ifdef block testing for a HAS_PARMETIS flag, with a null op alternative definition if it is not defined.  

The client code in pdgssvx.c and pzgssvx.c should be safe, already testing if permc_spec == PARMETIS.

**Comment by xiaoyeli** [comment]
Thanks.  Per your suggestion, we have made the changes with cpp
HAVE_PARMETIS to provide option not to link with parmetis library.

Sherry Li

**Comment by RizzerOnGitHub** [comment]
Thanks Sherry.

**Comment by RizzerOnGitHub** [comment]
Thanks Sherry.  The parmetis handling looks good now.
