### ISSUE TITLE
Specify the C standard.

### ISSUE THREAD

**Issue by haampie** [xiaoyeli/superlu_dist#152]
Your project does not define `CMAKE_C_STANDARD` in `CMakeLists.txt`

Not specifying the standard makes CMake leave the standard to compiler defaults, which change over time, yet the code is written in a specific C standard.

It looks like you're using C99 with extensions.

In https://github.com/xiaoyeli/superlu_dist/issues/46 it's mentioned that `-std=c99` should be used, but that's currently wrong, because [`putenv`](https://github.com/xiaoyeli/superlu_dist/blob/0c9ea165c25da7cc432623b254eddfcfea7179e7/TEST/pdtest.c#L501) is used; the man page says

```
$ man putenv
...

   Feature Test Macro Requirements for glibc (see feature_test_macros(7)):

       putenv():
           _XOPEN_SOURCE
               || /* glibc >= 2.19: */ _DEFAULT_SOURCE
               || /* glibc <= 2.19: */ _SVID_SOURCE
```

so it is an extension, and `#define _XOPEN_SOURCE` is required.

Please set

```cmake
set(CMAKE_C_STANDARD 99)
```

and either

```cmake
set(CMAKE_C_EXTENSIONS ON)
```

or update the relevant source files with

```c
#define _XOPEN_SOURCE
#include <stdlib.h>

... putenv(...) ...
```

**Comment by xiaoyeli** [comment]
@haampie 
If I define the followiing:
set(CMAKE_C_STANDARD 99)

We are still able to use the newer standard, like c11, c17, and c23, etc., right?
We don't want to be tied with old the old standard, like c99 and older.

**Comment by haampie** [comment]
Ah, I think `CMAKE_C_STANDARD` is rather the other way around (confusingly). If the compiler supports `-std=gnu99` it'll use that, if not it'll fall back to an _older_ standard. Not sure what the point of that is...

Digging further, looks like [this](https://cmake.org/cmake/help/latest/prop_gbl/CMAKE_C_KNOWN_FEATURES.html#high-level-meta-features-indicating-c-standard-support) is more promising for a lowerbound:

> If the compiler's default standard level is at least that of the requested feature, CMake may omit the -std= flag.

So maybe

```cmake
target_compile_features(<target> PUBLIC c_std_99)
```

is what you want

**Comment by xiaoyeli** [comment]
Thanks. I implemented this.

**Comment by osborn9** [comment]
@xiaoyeli  We're building via spack (to test with hypre) using gcc 4.8.5 and this spack change https://github.com/spack/spack/pull/40729 broke our build. 

A potential fix related to this discussion is [c99_fix.txt](https://github.com/xiaoyeli/superlu_dist/files/13290871/c99_fix.txt)
```
diff --git a/SRC/CMakeLists.txt b/SRC/CMakeLists.txt
index 8df55e0f..25ed424a 100644
--- a/SRC/CMakeLists.txt
+++ b/SRC/CMakeLists.txt
@@ -287,9 +287,12 @@ endif()
 target_sources(superlu_dist PRIVATE ${sources} ${HEADERS})
 set(targets superlu_dist)

+target_compile_features(superlu_dist PUBLIC c_std_99)
+
 if (BUILD_SHARED_LIBS AND BUILD_STATIC_LIBS)
   # build both shared and static libs
   target_sources(superlu_dist-static PRIVATE ${sources} ${HEADERS})
+  target_compile_features(superlu_dist-static PUBLIC c_std_99)
   list(APPEND targets superlu_dist-static)
 endif()
```

**Comment by xiaoyeli** [comment]
@osborn9  I forgot to add those 2 lines for the target libraries. Please try now.

**Comment by osborn9** [comment]
Fixed. Thanks!
