### ISSUE TITLE
Project version number

### ISSUE THREAD

**Issue by sagitter** [xiaoyeli/superlu_dist#153]
Hi all.

The project version number of `superlu_dist-8.2.0` is still `8.1.2`:
https://github.com/xiaoyeli/superlu_dist/blob/3fe6856d49252ddc2edd81a2ef0cd6092e144696/CMakeLists.txt#L13-L15

**Comment by xiaoyeli** [comment]
I forgot to commit the version number changes in several files. I just committed now.
How do I re-package a release tarball on giithub?

**Comment by sagitter** [comment]
> How do I re-package a release tarball on giithub?

https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository#editing-a-release

**Comment by xiaoyeli** [comment]
I can only edit/update the description, but the zip file
https://github.com/xiaoyeli/superlu_dist/archive/refs/tags/v8.2.0.zip
was not re-made.
Seems I have to delete the release, and re-release it?

**Comment by sagitter** [comment]
You have to change the release tag, i think, and leave the release number 8.2.0

**Comment by xiaoyeli** [comment]
unfortunately, this is already in the latest xSDK release: https://xsdk.info/installing-the-software/.
Just changing the release tag but keeping the same version will break all the dependencies.
Instead, I made a new release 8.2.1.
