### ISSUE TITLE
Implicit dependency between the python and fortran interface

### ISSUE THREAD

**Issue by yuyichao** [xiaoyeli/superlu_dist#174]
That's not handled by the build system.

https://github.com/xiaoyeli/superlu_dist/commit/6ec6acd0bcc890f96a09bcb90adad4a672c914f8 added the python target that depends on `config_f` which is a target in the `FORTRAN` directory. This causes the python build to fail without also enabling the fortran interface.

I noticed this since I had a build that disabled fortran but still have the python interface enabled since it was enabled by default. A check in the build system, which could be as simple as raising an explicit error, would be a lot better than the somewhat obscure `The dependency target "config_f" of target "superlu_dist_python" does not exist.` error message.

**Comment by liuyangzhuan** [comment]
Can you try this https://github.com/xiaoyeli/superlu_dist/commit/b3193e8615b5364f4e5650297d9e2aaf2e49c909 ?
The fortran dependency is not needed.

**Comment by yuyichao** [comment]
Seems to work fine. Thanks.
