### ISSUE TITLE
Error out due to enum MemType order change

### ISSUE THREAD

**Issue by mathsen** [xiaoyeli/superlu_dist#178]
Hello,
currently I have a case that errored out for me when running on more than four MPI processes. I debugged this and think that I have found a more general problem:
In [interLvl_symbfact()](https://github.com/xiaoyeli/superlu_dist/blob/b3eecd3eaac3a1332d0d2c5fc052d1af114df192/SRC/psymbfact.c#L472) I end up in calling [rl_update() here](https://github.com/xiaoyeli/superlu_dist/blob/b3eecd3eaac3a1332d0d2c5fc052d1af114df192/SRC/psymbfact.c#L4585) and another time [here](https://github.com/xiaoyeli/superlu_dist/blob/b3eecd3eaac3a1332d0d2c5fc052d1af114df192/SRC/psymbfact.c#L4596).
The fourteenth parameter is hard coded as ["1"](https://github.com/xiaoyeli/superlu_dist/blob/b3eecd3eaac3a1332d0d2c5fc052d1af114df192/SRC/psymbfact.c#L4588) or ["0"](https://github.com/xiaoyeli/superlu_dist/blob/b3eecd3eaac3a1332d0d2c5fc052d1af114df192/SRC/psymbfact.c#L4599) and is [int computeL](https://github.com/xiaoyeli/superlu_dist/blob/b3eecd3eaac3a1332d0d2c5fc052d1af114df192/SRC/psymbfact.c#L3338).
This is later passed to [expand_RL()](https://github.com/xiaoyeli/superlu_dist/blob/b3eecd3eaac3a1332d0d2c5fc052d1af114df192/SRC/psymbfact.c#L3575) which again passes it to [psymbfact_LUXpand_RL()](https://github.com/xiaoyeli/superlu_dist/blob/b3eecd3eaac3a1332d0d2c5fc052d1af114df192/SRC/psymbfact.c#L3313).
This function uses it internally as [int_t mem_type,](https://github.com/xiaoyeli/superlu_dist/blob/b3eecd3eaac3a1332d0d2c5fc052d1af114df192/SRC/psymbfact_util.c#L404) and makes some tests on it [here](https://github.com/xiaoyeli/superlu_dist/blob/b3eecd3eaac3a1332d0d2c5fc052d1af114df192/SRC/psymbfact_util.c#L435) and [here](https://github.com/xiaoyeli/superlu_dist/blob/b3eecd3eaac3a1332d0d2c5fc052d1af114df192/SRC/psymbfact_util.c#L440), where we compare it against members of [enum MemType](https://github.com/xiaoyeli/superlu_dist/blob/b3eecd3eaac3a1332d0d2c5fc052d1af114df192/SRC/superlu_enum_consts.h#L37).
We explicitly compare the passed integer values "1" and "0" against ["LSUB"](https://github.com/xiaoyeli/superlu_dist/blob/b3eecd3eaac3a1332d0d2c5fc052d1af114df192/SRC/psymbfact_util.c#L435) and ["USUB"](https://github.com/xiaoyeli/superlu_dist/blob/b3eecd3eaac3a1332d0d2c5fc052d1af114df192/SRC/psymbfact_util.c#L440C27-L440C31).
[Commit e207691](https://github.com/xiaoyeli/superlu_dist/commit/e2076918152efa9a6d44bf87e4c7fef9efd6d5d2#diff-4964d63c55baaf45c54e2d8b0485e230848b1a9da1d7c9fa40bdc3f77442c08d) changed the ordering of the enum from:

````
typedef enum {USUB, LSUB, UCOL, LUSUP, LLVL, ULVL, NO_MEMTYPE}  MemType;
````

to:
````
typedef enum {LUSUP, UCOL, LSUB, USUB, LLVL, ULVL, NO_MEMTYPE}  MemType;
````

So we now compare the passed value "0" to LSUB, which is "2" after the commit and we end up in the [else part](https://github.com/xiaoyeli/superlu_dist/blob/b3eecd3eaac3a1332d0d2c5fc052d1af114df192/SRC/psymbfact_util.c#L446) and error out.
So if we end up in [rl_update() here](https://github.com/xiaoyeli/superlu_dist/blob/b3eecd3eaac3a1332d0d2c5fc052d1af114df192/SRC/psymbfact.c#L4585) with the hard coded values of "1" and "0" and reach later [psymbfact_LUXpand_RL()](https://github.com/xiaoyeli/superlu_dist/blob/b3eecd3eaac3a1332d0d2c5fc052d1af114df192/SRC/psymbfact_util.c#L396) we basically intentionally enforce an error out.

This issue was released with version v8.2.0 already and for me it is unclear, why this change has been made. It is unrelated to the [commit message](https://github.com/xiaoyeli/superlu_dist/commit/e2076918152efa9a6d44bf87e4c7fef9efd6d5d2):

> Support use of putenv() in TEST/: add #define _XOPEN_SOURCE, and specify the minimum compiler standard in CMakeeLists.

I simply undid this change:

````
diff --git a/SRC/superlu_enum_consts.h b/SRC/superlu_enum_consts.h
index 311e068e..0f2f7164 100644
--- a/SRC/superlu_enum_consts.h
+++ b/SRC/superlu_enum_consts.h
@@ -34,8 +34,8 @@ typedef enum {NATURAL, MMD_ATA, MMD_AT_PLUS_A, COLAMD,
 typedef enum {NOTRANS, TRANS, CONJ}                             trans_t;
 typedef enum {NOEQUIL, ROW, COL, BOTH}                          DiagScale_t;
 typedef enum {NOREFINE, SLU_SINGLE=1, SLU_DOUBLE, SLU_EXTRA}    IterRefine_t;
-typedef enum {LUSUP, UCOL, LSUB, USUB, LLVL, ULVL, NO_MEMTYPE}  MemType;
-//typedef enum {USUB, LSUB, UCOL, LUSUP, LLVL, ULVL, NO_MEMTYPE}  MemType;
+//typedef enum {LUSUP, UCOL, LSUB, USUB, LLVL, ULVL, NO_MEMTYPE}  MemType;
+typedef enum {USUB, LSUB, UCOL, LUSUP, LLVL, ULVL, NO_MEMTYPE}  MemType;
 typedef enum {HEAD, TAIL}                                       stack_end_t;
 typedef enum {SYSTEM, USER}                                     LU_space_t;
 typedef enum {ONE_NORM, TWO_NORM, INF_NORM}                    norm_t;
````

And this leads to a working SuperLU_dist for me again. I think this problem should be also present in current v9.1.0 and master branch (although I did not test it).
Maybe someone could help me here?

Thanks and many greetings
mathsen

**Comment by xiaoyeli** [comment]
I changed the order of the enum names to be consistent with serial and multithreaded SuperLU versions.
The bug you mentioned was fixed a few months ago, see [this line](https://github.com/xiaoyeli/superlu_dist/blob/fe0e4e8968c58309fd75b4d6999580c44fffc26d/SRC/prec-independent/psymbfact.c#L3320)
You are probably using an older version of the code.

**Comment by mathsen** [comment]
@xiaoyeli Thanks for the reply and explanation! Indeed I used SuperLU_dist through Trilinos (Amesos2) and used version 7.2.0 all the time. Upgrading to 8.2.1 lead to quite unstable behavior that I could quickly debug recently and which was all due to this change in the enum.
Upgrading to version 9 leads unfortunately again to crashes in SuperLU_dist at runtime (which I currently don't have the time to debug or work on).
Since this issue is fixed in current versions, I will close this here.
