### ISSUE TITLE
LSUB/USUB definition

### ISSUE THREAD

**Issue by vyu16** [xiaoyeli/superlu_dist#19]
I encountered a problem in the 5.2.x version of SuperLU_DIST. Below is my understanding of the issue:

Definitions of LSUB and USUB were removed from psymbfact.h in the git commit ee9d053b2526c12f61fda985c61bf1ba240ceac5, as the two macros are defined elsewhere (in superlu_enum_consts.h).

LSUB and USUB used to be 1 and 0 in psymbfact.h. Now they are 2 and 3 as defined in superlu_enum_consts.h.

However, hard-coded 0 and 1 are still passed into the function psymbfact_LUXpand_RL in psymbfact_util.c, while the function only recognizes LSUB and USUB, which are 2 and 3. So the calculation always ends up with "Tries to expand nonexisting memory type".

**Comment by xiaoyeli** [comment]
I just fixed this in the master branch.

**Comment by vyu16** [comment]
Thanks a lot! It worked with my test case.
