### ISSUE TITLE
GPU code calls sp_ienv instead of sp_ienv_dist

### ISSUE THREAD

**Issue by mstud** [xiaoyeli/superlu_dist#37]
in zscatter.c and dscatter.c when ACC=GPU is enabled, one get's an "undefined reference" compile error because sp_ienv() is called but the function name is sp_ienv_dist()

**Comment by xiaoyeli** [comment]
Thanks for pointing this out.  I fixed this in the master branch.  It will show up in the next release.

Sherry Li
