### ISSUE TITLE
variable 'send_req' is being used without being initialized

### ISSUE THREAD

**Issue by xuanvinhilb** [xiaoyeli/superlu_dist#38]
Hi all,

I am using superLU_DIST via PETSc package. I have a small piece of code (compiled in debug mode of VS2015) which call superLU_DIST for the solution of a linear system.
However, the program crashed when calling KSPSolve() (which in turn which ask superLU_DIST to solve the system) with the error "The variable 'send_req' is being used without initialized." (attached in the picture). 
Unfortunately, I am not be able to track down where in superLU code the variable is not initialized.
Could you please check whether this is the bug of superLU_DIST?

Thank and kind regards,

![untitled](https://user-images.githubusercontent.com/25169998/51323941-c7f32600-1a69-11e9-9877-f8f1964b7ad0.png)

**Comment by xiaoyeli** [comment]
Fixed, on GitHub and a new release v6.1.1.
