### ISSUE TITLE
superlu_dist.pc.in provides -lsuperlu not -lsuperlu_dist

### ISSUE THREAD

**Issue by RizzerOnGitHub** [xiaoyeli/superlu_dist#44]
superlu_dist.pc.in is used to generate superlu_dist's pkg-config file. It contains 
`Libs: -L${libdir} -lsuperlu`

I think this should be
`Libs: -L${libdir} -lsuperlu_dist`

**Comment by xiaoyeli** [comment]
Yes, corrected.
