### ISSUE TITLE
valgrind memory errors via petsc

### ISSUE THREAD

**Issue by balay** [xiaoyeli/superlu_dist#49]
@xiaoyeli we are seeing valgrind error messages in superlu_dist via petsc

https://gitlab.com/petsc/petsc/issues/439

Could you take a look at this issue?
thanks,

**Comment by balay** [comment]
The following changes fixes the problem for  me. But they might be masking some other issues.
Esp the first one (the change is in petsc) - its strange I would have to zero the struct - where we would expect `PStatInit()` would correcty initialize the struct

```
diff --git a/src/mat/impls/aij/mpi/superlu_dist/superlu_dist.c b/src/mat/impls/aij/mpi/superlu_dist/superlu_dist.c
index fde462c493..e27bd16f98 100644
--- a/src/mat/impls/aij/mpi/superlu_dist/superlu_dist.c
+++ b/src/mat/impls/aij/mpi/superlu_dist/superlu_dist.c
@@ -119,6 +119,7 @@ static PetscErrorCode MatSolve_SuperLU_DIST(Mat A,Vec b_mpi,Vec x)
   ierr = VecCopy(b_mpi,x);CHKERRQ(ierr);
   ierr = VecGetArray(x,&bptr);CHKERRQ(ierr);
 
+  ierr = PetscMemzero(&stat,sizeof(stat));CHKERRQ(ierr);
   PetscStackCall("SuperLU_DIST:PStatInit",PStatInit(&stat));        /* Initialize the statistics variables. */
 #if defined(PETSC_USE_COMPLEX)
     PetscStackCall("SuperLU_DIST:pzgssvx",pzgssvx(&lu->options,&lu->A_sup,&lu->ScalePermstruct,(doublecomplex*)bptr,m,1,&lu->grid,&lu->LUstruct,&lu->SOLVEstruct,berr,&stat,&info));

```

```
diff --git a/SRC/pdgstrs.c b/SRC/pdgstrs.c
index 7d1d108..9b07b81 100644
--- a/SRC/pdgstrs.c
+++ b/SRC/pdgstrs.c
@@ -1076,6 +1076,8 @@ pdgstrs(int_t n, LUstruct_t *LUstruct,
 #endif
     if ( !(x = (double*)SUPERLU_MALLOC((ldalsum * nrhs + nlb * XK_H) * sizeof(double))) )
        ABORT("Calloc fails for x[].");
+    for ( ii=0; ii < ldalsum * nrhs + nlb * XK_H; ii++ )
+       x[ii]=zero;
 
 
     sizertemp=ldalsum * nrhs;
```

**Comment by xiaoyeli** [comment]
I don't understand why "stat" struct needs to be zeroed.

For the second one, I changed malloc to calloc, updated "master".  It will be in the next tarball release.

**Comment by balay** [comment]
@xiaoyeli could you add this patch to `maint` branch? This way we can use it from current petsc release/maint [which is using `superlu-dist-6.1.1`]. Also don't fixes in maint  get merged to master?

Wrt `PStatInit()` - I see:
```
void
PStatInit(SuperLUStat_t *stat)
{
    register int_t i;

    if ( !(stat->utime = SUPERLU_MALLOC(NPHASES*sizeof(double))) )
	ABORT("Malloc fails for stat->utime[]");
    if ( !(stat->ops = (flops_t *) SUPERLU_MALLOC(NPHASES * sizeof(flops_t))) )
        ABORT("SUPERLU_MALLOC fails for stat->ops[]");
    for (i = 0; i < NPHASES; ++i) {
        stat->utime[i] = 0.;
        stat->ops[i] = 0.;
    }
    stat->TinyPivots = stat->RefineSteps = 0;
}
```

So this routine assumes the values of the structure is set before `PStatInit()` is called?
This is not the source of the current error - but I assume similar code exists elseware in superlu_dist causing this valgrind issue.

So I was assuming  PStatInit() would initialize the stat datastructure - and not read its contents before initializing..

**Comment by xiaoyeli** [comment]
I applied to "maint".
I don't understand the issue with "stat" structure. This routine just initialize some variables in the structure. This is called at the beginning of a program.

**Comment by balay** [comment]
sorry - I was misreading the above code earlier..

However the code is initializing a few members of the struct - but not all.

The valgrind error was on:
```
#       ==2937345==    at 0x69EF7D1: log_memory (util.c:1107)
```
That is:
```
            SUPERLU_MAX(stat->peak_buffer, stat->current_buffer);
```
Ok  try initializing these members of the struct
```
diff --git a/SRC/util.c b/SRC/util.c
index 225547d..d9d02e8 100644
--- a/SRC/util.c
+++ b/SRC/util.c
@@ -668,6 +668,7 @@ PStatInit(SuperLUStat_t *stat)
         stat->ops[i] = 0.;
     }
     stat->TinyPivots = stat->RefineSteps = 0;
+    stat->peak_buffer = stat->current_buffer = 0;
 }
 
 void
```
The test is valgrind clean after this change

There are a few more members in this struct.  They also probably need initialization.

**Comment by balay** [comment]
@xiaoyeli could you make sure the above patch goes into maint and the new release?

Also can you make sure all the fixes in maint are included in master and the new release?
```
balay@sb /home/balay/git-repo/github/superlu_dist (master=)
$ git log master..maint --no-merges --oneline
de58c8f (origin/maint, maint) + update run_cmake_build.sh, add "-O" in C_FLAGS; CBLAS/ has problem with "-g" only + CMakeLists.txt: move set(CMAKE_POSITION_INDEPENDENT_CODE ON)   in "if (BUILD_SHARED_LIBS)" branch + in pdgstrs.c [1076]: change x = SUPERLU_MALLOC() to x = doubleCalloc_dist()   (Satish reported Valgrind complaining uninitialized byte through petsc.)
b153ac4 (balay/fix-superlu-dist-mkl-blas-confusion) fix superlu-dist blas/lapack detection - which fails with MKL and picks up system blas
e2bee7e untrack superlu_dist_config.h
balay@sb /home/balay/git-repo/github/superlu_dist (master=)
$ 
```
thanks,

**Comment by xiaoyeli** [comment]
@balay I made a new release 6.2.0:
https://portal.nersc.gov/project/sparse/superlu/superlu_dist_6.2.0.tar.gz
incorporated all the changes mentioned this week.
Master and maint are sync'ed with this release on GitHub.
