### ISSUE TITLE
Can PT-SCOTCH be used with SuperLU_DIST?

### ISSUE THREAD

**Issue by congcongxn** [xiaoyeli/superlu_dist#57]
Hi, I'm wondering if it's possible to use PT-SCOTCH together with SuperLU_DIST. Looks like PT-SCOTCH is ParMETIS-compatible, but how to make it work with SuperLU_DIST is not clear to me. Are there any instructions anywhere? Thanks!

**Comment by xiaoyeli** [comment]
I believe you can use the same interface, but just link with PT_SCOTCH (use its ParMetis interface), not to link ParMetis library.

**Comment by congcongxn** [comment]
Hi @xiaoyeli , thank you for the answer. I started with the current master branch of SuperLU_DIST and did some experiments.

With ParMETIS I used the following flags to build SuperLU_DIST:

<details>

```
cmake .. \
  -DTPL_PARMETIS_INCLUDE_DIRS="/home/ccxn/opt/parmetis-4.0.3/include" \
  -DTPL_PARMETIS_LIBRARIES="/home/ccxn/opt/parmetis-4.0.3/lib/libparmetis.a;/home/ccxn/opt/parmetis-4.0.3/lib/libmetis.a" \
  -DCMAKE_C_COMPILER=mpicc \
  -DCMAKE_C_FLAGS="-std=c99 -O0 -g -DPRNTlevel=1 -DDEBUGlevel=1" \
  -DCMAKE_CXX_COMPILER=mpicxx \
  -DCMAKE_CXX_FLAGS="-std=c++11 -O0 -g -DPRNTlevel=1 -DDEBUGlevel=1" \
  -DCMAKE_Fortran_COMPILER=mpif90 \
  -DCMAKE_Fortran_FLAGS="-O0 -g" \
  -DTPL_ENABLE_BLASLIB=OFF \
  -DTPL_ENABLE_LAPACKLIB=ON \
  -DTPL_ENABLE_COMBBLASLIB=OFF \
  -DTPL_ENABLE_PARMETISLIB=ON
```

</details>

All the tests passed without any problem.

Then I just changed ParMETIS 4.0.3 to PT-SCOTCH 6.0.9:

<details>

```
cmake .. \
  -DTPL_PARMETIS_INCLUDE_DIRS="/home/ccxn/opt/scotch_6.0.9/include" \
  -DTPL_PARMETIS_LIBRARIES="/home/ccxn/opt/scotch_6.0.9/lib/libptscotchparmetis.a;/home/ccxn/opt/scotch_6.0.9/lib/libptscotch.a;/home/ccxn/opt/scotch_6.0.9/lib/libptscotcherr.a;/home/ccxn/opt/scotch_6.0.9/lib/libscotchmetis.a;/home/ccxn/opt/scotch_6.0.9/lib/libscotch.a;/home/ccxn/opt/scotch_6.0.9/lib/libscotcherr.a" \
  -DCMAKE_C_COMPILER=mpicc \
  -DCMAKE_C_FLAGS="-std=c99 -O0 -g -DPRNTlevel=1 -DDEBUGlevel=1" \
  -DCMAKE_CXX_COMPILER=mpicxx \
  -DCMAKE_CXX_FLAGS="-std=c++11 -O0 -g -DPRNTlevel=1 -DDEBUGlevel=1" \
  -DCMAKE_Fortran_COMPILER=mpif90 \
  -DCMAKE_Fortran_FLAGS="-O0 -g" \
  -DTPL_ENABLE_BLASLIB=OFF \
  -DTPL_ENABLE_LAPACKLIB=ON \
  -DTPL_ENABLE_COMBBLASLIB=OFF \
  -DTPL_ENABLE_PARMETISLIB=ON
```

</details>

The compilation finished fine, meaning that PT-SCOTCH indeed provides the same symbols as in ParMETIS, I think.

Then the tests all failed with segmentation faults when calling `ParMETIS_V3_NodeND` in `get_perm_c_parmetis.c`.

Do you see any mistakes in the way I built SuperLU_DIST? If not then I think it's probably a problem in PT-SCOTCH. Feel free to close this issue if you think it's not relevant to SuperLU_DIST.

By the way I found the CMake option `TPL_ENABLE_BLASLIB` quite misleading. If I'm reading the CMake files correctly, it actually means whether or not the BLAS shipped with SuperLU_DIST should be used, instead of whether or not BLAS should be used in general. I think it's not a bad idea to rename it with something like `TPL_ENABLE_INTERNAL_BLASLIB`. Just a suggestion.

**Comment by pghysels** [comment]
One issue could be the integer size, if PT-SCOTCH is compiled for 64-bit integers and SuperLU_dist uses the 32-bit ParMETIS interface, you can get segfaults.
Try compiling PT-SCOTCH with `-DINTSIZE32` .
PT-SCOTCH also has the option `-DSCOTCH_PARMETIS_VERSION=x`, but that only supports v3, so I think that should be good.

**Comment by xiaoyeli** [comment]
@congcongxn  It's a good idea to rename TPL_ENABLE_BLASLIB to TPL_ENABLE_INTERNAL_BLASLIB.  I have updated the master branch.

**Comment by congcongxn** [comment]
@xiaoyeli @pghysels Thank you! I defined `-DINTSIZE32` and `-DSCOTCH_PARMETIS_VERSION=3` but they didn't help. Then I found `-DSCOTCH_METIS_VERSION=5` should also be defined (default is 3). Everything good now. Thanks!

**Comment by xiaoyeli** [comment]
I updated README.md.
