### ISSUE TITLE
pddrive run error

### ISSUE THREAD

**Issue by afrah** [xiaoyeli/superlu_dist#6]
I installed superlu_dist version 5.1.2 but when I ran make pddrive in the Example folder , I got this error

> usr/share/mpich-install/bin/mpicc -Wl,-rpath,/home/afrah/SuperLU_DIST_5.1.2/lib   -Wl,-rpath  -Wl,/usr/share/mpich-install/lib  -Wl,--enable-new-dtags -fopenmp pddrive.o dcreate_matrix.o  /home/afrah/SuperLU_DIST_5.1.2/build/SRC/libsuperlu_dist.so /usr/lib/libblas.so /usr/share/parmetis/lib/libparmetis.so /usr/share/parmetis/lib/libmetis.a -lm -o pddrive
> /home/afrah/SuperLU_DIST_5.1.2/build/SRC/libsuperlu_dist.so: undefined reference to `dgemv'
> /home/afrah/SuperLU_DIST_5.1.2/build/SRC/libsuperlu_dist.so: undefined reference to `dger'
> /home/afrah/SuperLU_DIST_5.1.2/build/SRC/libsuperlu_dist.so: undefined reference to `dtrsm'
> /home/afrah/SuperLU_DIST_5.1.2/build/SRC/libsuperlu_dist.so: undefined reference to `zgeru'
> /home/afrah/SuperLU_DIST_5.1.2/build/SRC/libsuperlu_dist.so: undefined reference to `zgemv'
> /home/afrah/SuperLU_DIST_5.1.2/build/SRC/libsuperlu_dist.so: undefined reference to `ztrsm'
> /home/afrah/SuperLU_DIST_5.1.2/build/SRC/libsuperlu_dist.so: undefined reference to `zgemm'
> /home/afrah/SuperLU_DIST_5.1.2/build/SRC/libsuperlu_dist.so: undefined reference to `ztrsv'
> /home/afrah/SuperLU_DIST_5.1.2/build/SRC/libsuperlu_dist.so: undefined reference to `dgemm'
> /home/afrah/SuperLU_DIST_5.1.2/build/SRC/libsuperlu_dist.so: undefined reference to `dtrsv'
> collect2: error: ld returned 1 exit status
> Makefile:70: recipe for target 'pddrive' failed
> make: *** [pddrive] Error 1
> 

Any help please

**Comment by kruger** [comment]
Those symbols are blas/lapack symbols.  If you try this:

> nm /usr/lib/libblas.so | grep zgemm 

you will see the symbol.  Most likely your blas has an underscore and you need to set the C definitions to fix it.  You can try adding this flag: "-DCMAKE_C_FLAGS:STRING='-DAdd_'  to your cmake line or edit  SRC/CNames.h.  See the README for more details.

**Comment by afrah** [comment]
When I compile pddrive with mpicc pddrive.c , if=t gave me this error:

> EXAMPLE/pddrive.c:25:27: fatal error: superlu_ddefs.h: No such file or directory
compilation terminated.

so I modified the file by adding the patth to  superlu_ddefs.h . But now Igot the fi=ollowibg error:

> /tmp/ccuCVN1w.o: In function `main':
/home/afrah/SuperLU_DIST_5.1.2/EXAMPLE/pddrive.c:101: undefined reference to `superlu_abort_and_exit_dist'
/home/afrah/SuperLU_DIST_5.1.2/EXAMPLE/pddrive.c:110: undefined reference to `superlu_gridinit'
/home/afrah/SuperLU_DIST_5.1.2/EXAMPLE/pddrive.c:131: undefined reference to `dcreate_matrix'
/home/afrah/SuperLU_DIST_5.1.2/EXAMPLE/pddrive.c:133: undefined reference to `doubleMalloc_dist'
/home/afrah/SuperLU_DIST_5.1.2/EXAMPLE/pddrive.c:134: undefined reference to `superlu_abort_and_exit_dist'
/home/afrah/SuperLU_DIST_5.1.2/EXAMPLE/pddrive.c:153: undefined reference to `set_default_options_dist'
/home/afrah/SuperLU_DIST_5.1.2/EXAMPLE/pddrive.c:163: undefined reference to `print_sp_ienv_dist'
/home/afrah/SuperLU_DIST_5.1.2/EXAMPLE/pddrive.c:164: undefined reference to `print_options_dist'
/home/afrah/SuperLU_DIST_5.1.2/EXAMPLE/pddrive.c:171: undefined reference to `ScalePermstructInit'
/home/afrah/SuperLU_DIST_5.1.2/EXAMPLE/pddrive.c:172: undefined reference to `LUstructInit'
/home/afrah/SuperLU_DIST_5.1.2/EXAMPLE/pddrive.c:175: undefined reference to `PStatInit'
/home/afrah/SuperLU_DIST_5.1.2/EXAMPLE/pddrive.c:178: undefined reference to `pdgssvx'
/home/afrah/SuperLU_DIST_5.1.2/EXAMPLE/pddrive.c:183: undefined reference to `pdinf_norm_error'
/home/afrah/SuperLU_DIST_5.1.2/EXAMPLE/pddrive.c:186: undefined reference to `PStatPrint'
/home/afrah/SuperLU_DIST_5.1.2/EXAMPLE/pddrive.c:192: undefined reference to `PStatFree'
/home/afrah/SuperLU_DIST_5.1.2/EXAMPLE/pddrive.c:193: undefined reference to `Destroy_CompRowLoc_Matrix_dist'
/home/afrah/SuperLU_DIST_5.1.2/EXAMPLE/pddrive.c:194: undefined reference to `ScalePermstructFree'
/home/afrah/SuperLU_DIST_5.1.2/EXAMPLE/pddrive.c:195: undefined reference to `Destroy_LU'
/home/afrah/SuperLU_DIST_5.1.2/EXAMPLE/pddrive.c:196: undefined reference to `LUstructFree'
/home/afrah/SuperLU_DIST_5.1.2/EXAMPLE/pddrive.c:198: undefined reference to `dSolveFinalize'
/home/afrah/SuperLU_DIST_5.1.2/EXAMPLE/pddrive.c:200: undefined reference to `superlu_free_dist'
/home/afrah/SuperLU_DIST_5.1.2/EXAMPLE/pddrive.c:201: undefined reference to `superlu_free_dist'
/home/afrah/SuperLU_DIST_5.1.2/EXAMPLE/pddrive.c:202: undefined reference to `superlu_free_dist'
/home/afrah/SuperLU_DIST_5.1.2/EXAMPLE/pddrive.c:208: undefined reference to `superlu_gridexit'
collect2: error: ld returned 1 exit status


Do you have any idea

**Comment by xiaoyeli** [comment]
Can you send me the make.inc file?  Or are you using CMake to compile?

Sherry Li
