### ISSUE TITLE
Makefile link vs library fails

### ISSUE THREAD

**Issue by pguthrey** [xiaoyeli/superlu_dist#61]
I am attempting to use superlu_dist in my project as a git submodule. 
I use the following script to install superLU_dist. 

https://gist.github.com/pguthrey/4cc27b3c5eaf0601c16518121e69dee4

All tests pass. So far so good.  Then my makefile is as such:

```
SUPERLUDIR = $(SUBMODULES)/superlu_dist/build
SUPERLU_INCLUDE = -I$(SUPERLUDIR)/include
SUPERLU_LIBS = -L$(SUPERLUDIR)/lib64 -lsuperlu_dist
CXX = mpic++
LINK = time $(CXX) -std=c++11 -O3 -DTIMER -DTIMINGS -DENABLE_MPI -DENABLE_OPENMP -fopenmp $(FLAGS) --link $(SUPERLU_LIBS)
FFLAGS = -c $(INCLUDE_LIBS) $(SUPERLU_INCLUDE)
COMPILE = $(LINK) $(FFLAGS) 
```

When I compile, everything seems fine except for a warning
```
icpc_orig: command line warning #10006: ignoring unknown option '-flink'
```
When I try to run the exe, I get 

```
myprogram.exe: error while loading shared libraries: libsuperlu_dist.so.6: cannot open shared object file: No such file or directory
```
So it seems that I cannot find the shared object file, and yet they seem to be in the expected location
```
$ find ./* -name "libsuperlu_dist.so.6"
./build/lib64/libsuperlu_dist.so.6
./build/SRC/libsuperlu_dist.so.6
```
Am I misinterpreting something here?

**Comment by pguthrey** [comment]
It seems that the modification 
```
SUPERLU_LIBS = -L$(SUPERLUDIR)/lib64  -lsuperlu_dist -Wl,-rpath $(SUPERLUDIR)/lib64 -lsuperlu_dist
```
helps, but I am not sure if this is the intended way for this to work...?

**Comment by xiaoyeli** [comment]
Yes, to link with a shared library, you often need to specify 'rpath'.  There must be a way to add this automatically in make.inc.in, so  CMake can produce correct make.inc.  But I haven't investigated it.
