### ISSUE TITLE
Version of CombBLAS needed for SuperLU_Dist v5.4?

### ISSUE THREAD

**Issue by JustinClough** [xiaoyeli/superlu_dist#62]
What version of CombBLAS is needed to build SuperLU_Dist v5.4.0 ([specifically this tag](https://github.com/xiaoyeli/superlu_dist/tree/v5.4.0))? If it's not versions 1.6.1 or 1.6.2 of CombBLAS, then where can I find the files?

I specifically need to build v5.4.0 of SuperLU_Dist for compatibility with another project. Here are two related issues in that project's repo that mention this specific version: 
1. https://github.com/trilinos/Trilinos/issues/6892
2. https://github.com/trilinos/Trilinos/issues/7708#issuecomment-665394384

I have tried to compile v5.4 with CombBLAS versions 1.6.1 and 1.6.2 but have run into issues. For both CombBLAS versions, it first appears that SuperLU_Dist expects a different file structure. Then with enough symbolic links, I can get SuperLU_Dist to compile, but then all of the tests fail with seg-faults. Most CombBLAS tests pass so I don't think the CombBLAS installations are the root of the issue. 

I have also seen CombBLAS v2.0+ but haven't tried to compile it. Comparing release dates between CombBLAS v1.6.* and SuperLU_Dist, I think I need an earlier version of CombBLAS. I haven't been able to find earlier version; if I was, it would really help to know the right version as opposed to guess-and-check. 

For completeness:
This is where I'm downloading my CombBLAS v1.6.1 and 1.6.2 tarballs: https://people.eecs.berkeley.edu/~aydin/CombBLAS/html/
I have seen CombBLAS v2.+ hosted here: https://bitbucket.org/berkeleylab/combinatorial-blas-2.0/src/master/

I may also be off in my hunch that it's a version miss-match issue. Is there a special way to compile CombBLAS to interact with SuperLU_Dist v5.4.0?

Let me know if I can provide any more info. Thanks in advance!

**Comment by xiaoyeli** [comment]
I am adding Aydin Buluc in the email; he is in charge of CombBLAS release.

Aydin :
superlu_dist v5.4.0 is the first time CombBLAS is used, the date is June 1,
2018, see release history here:
https://portal.nersc.gov/project/sparse/superlu/#superlu_dist

Probably at that time we were using CombBLAS beta release. Can you please
check your various version dates?  Perhaps send this early version to the
user?

Thanks,
Sherry

**Comment by xiaoyeli** [comment]
It should be CombBLAS v1.6.1 by that time:
https://people.eecs.berkeley.edu/~aydin/CombBLAS_FILES/release-notes.html so
I don't think it is a versioning issue
But if Justin really wants to try an earlier version, v1.6.0 is here:
https://people.eecs.berkeley.edu/~aydin/CombBLAS_FILES/

Given that we have recently changed the structure (on bitbucket, i.e.
v2.0+) to make it less likely to have symbolic linking errors, it might be
worth trying

- Aydin

**Comment by JustinClough** [comment]
Thank you! I tried starting from scratch using CombBLAS v1.6.1 and Superlu_dist v5.4.0 but I'm still having issues compiling the later. I'm able to configure and generate with cmake but when I try to `make` I get this compilation error:
```
[  0%] Building CXX object SRC/CMakeFiles/superlu_dist.dir/c2cpp_GetAWPM.cpp.o
cd /home/jlclough/research/trilinos_project/superlu_dist-5.4.0/build/SRC && /usr/bin/mpicxx  -DSUPERLU_DIST_EXPORTS -I/home/jlclough/research/trilinos_project/superlu_dist-5.4.0/build/SRC -I/home/jlclough/research/trilinos_project/parmetis-4.0.3/install/include -I/home/jlclough/research/trilinos_project/parmetis-4.0.3/install/metis/include -I/home/jlclough/research/trilinos_project/CombBLAS_beta_16_1 -I/home/jlclough/research/trilinos_project/CombBLAS_beta_16_1/Applications -I/home/jlclough/research/trilinos_project/CombBLAS_beta_16_1/BipartiteMatchings  -I/home/jlclough/research/trilinos_project/CombBLAS_beta_16_1//BipartiteMatchings -I/home/jlclough/research/trilinos_project/CombBLAS_beta_16_1//Applications -I/home/jlclough/research/trilinos_project/CombBLAS_beta_16_1/ -fopenmp  -fPIC -O3 -march=native -std=c++14   -o CMakeFiles/superlu_dist.dir/c2cpp_GetAWPM.cpp.o -c /home/jlclough/research/trilinos_project/superlu_dist-5.4.0/SRC/c2cpp_GetAWPM.cpp
In file included from /home/jlclough/research/trilinos_project/superlu_dist-5.4.0/SRC/c2cpp_GetAWPM.cpp:22:
/home/jlclough/research/trilinos_project/superlu_dist-5.4.0/SRC/AWPM_CombBLAS.hpp: In function ‘void GetAWPM(SuperMatrix*, gridinfo_t*, ScalePermstruct_t*)’:
/home/jlclough/research/trilinos_project/superlu_dist-5.4.0/SRC/AWPM_CombBLAS.hpp:91:60: error: ‘int combblas::SpParMat<IT, NT, DER>::Owner(IT, IT, IT, IT, LIT&, LIT&) const [with LIT = int; IT = int; NT = double; DER = combblas::SpDCCols<int, double>]’ is private within this context
   91 |             p = Adcsc.Owner(m, n , irow, jcol, lirow, ljcol);
      |                                                            ^
In file included from /home/jlclough/research/trilinos_project/CombBLAS_beta_16_1/SpParMat.h:423,
                 from /home/jlclough/research/trilinos_project/CombBLAS_beta_16_1/CombBLAS.h:125,
                 from /home/jlclough/research/trilinos_project/superlu_dist-5.4.0/SRC/AWPM_CombBLAS.hpp:5,
                 from /home/jlclough/research/trilinos_project/superlu_dist-5.4.0/SRC/c2cpp_GetAWPM.cpp:22:
/home/jlclough/research/trilinos_project/CombBLAS_beta_16_1/SpParMat.cpp:4270:5: note: declared private here
 4270 | int SpParMat<IT,NT,DER>::Owner(IT total_m, IT total_n, IT grow, IT gcol, LIT & lrow, LIT & lcol) const
      |     ^~~~~~~~~~~~~~~~~~~
In file included from /home/jlclough/research/trilinos_project/superlu_dist-5.4.0/SRC/c2cpp_GetAWPM.cpp:22:
/home/jlclough/research/trilinos_project/superlu_dist-5.4.0/SRC/AWPM_CombBLAS.hpp:98:64: error: ‘void combblas::SpParMat<IT, NT, DER>::SparseCommon(std::vector<std::vector<std::tuple<LIT, LIT, NT> > >&, LIT, IT, IT, _BinaryOperation) [with _BinaryOperation = std::plus<double>; LIT = int; IT = int; NT = double; DER = combblas::SpDCCols<int, double>]’ is private within this context
   98 |     Adcsc.SparseCommon(data, nnz_loc, m, n, std::plus<double>());
      |                                                                ^
In file included from /home/jlclough/research/trilinos_project/CombBLAS_beta_16_1/SpParMat.h:423,
                 from /home/jlclough/research/trilinos_project/CombBLAS_beta_16_1/CombBLAS.h:125,
                 from /home/jlclough/research/trilinos_project/superlu_dist-5.4.0/SRC/AWPM_CombBLAS.hpp:5,
                 from /home/jlclough/research/trilinos_project/superlu_dist-5.4.0/SRC/c2cpp_GetAWPM.cpp:22:
/home/jlclough/research/trilinos_project/CombBLAS_beta_16_1/SpParMat.cpp:2426:6: note: declared private here
 2426 | void SpParMat< IT,NT,DER >::SparseCommon(std::vector< std::vector < std::tuple<LIT,LIT,NT> > > & data, LIT locsize, IT total_m, IT total_n, _BinaryOperation BinOp)
      |      ^~~~~~~~~~~~~~~~~~~~~
In file included from /home/jlclough/research/trilinos_project/superlu_dist-5.4.0/SRC/c2cpp_GetAWPM.cpp:22:
/home/jlclough/research/trilinos_project/superlu_dist-5.4.0/SRC/AWPM_CombBLAS.hpp:101:15: error: ‘AWPM’ is not a member of ‘combblas’
  101 |     combblas::AWPM(Adcsc, mateRow2Col, mateCol2Row,true);
      |               ^~~~
make[2]: *** [SRC/CMakeFiles/superlu_dist.dir/build.make:352: SRC/CMakeFiles/superlu_dist.dir/c2cpp_GetAWPM.cpp.o] Error 1
make[2]: Leaving directory '/home/jlclough/research/trilinos_project/superlu_dist-5.4.0/build'
make[1]: *** [CMakeFiles/Makefile2:990: SRC/CMakeFiles/superlu_dist.dir/all] Error 2
make[1]: Leaving directory '/home/jlclough/research/trilinos_project/superlu_dist-5.4.0/build'
make: *** [Makefile:144: all] Error 2
```
Have you seen this error before? I understand that the root of it is that superlu_dist expects SpParMat(...) to be public whereas it's declared private in CombBLAS. I assumed that this function was made public in another version of CombBLAS which spurred the original question. 

Let me know if you need any machine or environment specific info.

**Comment by JustinClough** [comment]
Another update, I tried again with current CombBLAS v2.0 from the bitbucket link. I was able to get SuperLU_Dist v5.4.0 to compile. When I try running ctest, the first test seg-faults and hangs. Here's the output:
```
UpdateCTestConfiguration  from :/home/jlclough/research/trilinos_project/superlu_dist-5.4.0/build/DartConfiguration.tcl
Parse Config file:/home/jlclough/research/trilinos_project/superlu_dist-5.4.0/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/jlclough/research/trilinos_project/superlu_dist-5.4.0/build/DartConfiguration.tcl
Parse Config file:/home/jlclough/research/trilinos_project/superlu_dist-5.4.0/build/DartConfiguration.tcl
Test project /home/jlclough/research/trilinos_project/superlu_dist-5.4.0/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1
      Start  1: pdtest_1x1_1_2_8_20_SP

1: Test command: /usr/bin/mpirun "-n" "1" "pdtest" "-r" "1" "-c" "1" "-s" "1" "-b" "2" "-x" "8" "-m" "20" "-f" "/home/jlclough/research/trilinos_project/superlu_dist-5.4.0/EXAMPLE/g20.rua"
1: Test timeout computed to be: 1500
1: Time to read and distribute matrix 0.00
1:    Current memory used:         416 bytes
1:    Maximum memory used:         416 bytes
1: ***Memory allocation failed for OMETIS: cptr. Requested size: 12762012771898363016 bytes
1: [venus:96939] *** Process received signal ***
1: [venus:96939] Signal: Segmentation fault (11)
1: [venus:96939] Signal code: Address not mapped (1)
1: [venus:96939] Failing at address: 0x7f98000001bf
```

This is the same error I was getting with the heaps of symbolic links when I compiled with CombBLAS v1.6.1 and v1.6.2. How does the test determine the requested memory size? It's such a large number and changes with each run, I would guess that it's reading an uninitialized value. 

Again, please let me know what you think of the above and if it's indicative of anything particular. Thanks!

**Comment by xiaoyeli** [comment]
It's hard to say when went wrong.  Are you compiling with 32-bit integer or
64-bit?

Sherry

**Comment by JustinClough** [comment]
I'm compiling with 64-bit

**Comment by xiaoyeli** [comment]
Then, make sure METIS (or ParMETIS) needs to be compiled with 64-bit
integer as well.

Sherry

**Comment by JustinClough** [comment]
Okay, I just double checked. In my `metis.h` file, I have `#define IDXTYPEWIDTH 64`. From the ParMETIS instructions, I think that is all I need to compile with 64-bit integers. Am I missing anything else?

**Comment by xiaoyeli** [comment]
That's correct.  Then, I don't know what the problem is. It's difficult to
go back to older versions of both superlu and combblas.  I think the best
is to upgrade your superlu to latest?

Sherry

**Comment by JustinClough** [comment]
I'm starting to think that upgrading trilinos to work with the most recent release of superlu_dist is the best idea too. There's a few more leads that I want to track down before committing to moving on. 

In either case, thank you for the help! I'll let you know whether I get 5.4 working on my machine or start upgrading Trilinos.

**Comment by xiaoyeli** [comment]
great. I can certainly help this upgrade with Trilinos.    -Sherry
