### ISSUE TITLE
Negative "info" return value for pdgssvx is undocumented

### ISSUE THREAD

**Issue by joshessman-llnl** [xiaoyeli/superlu_dist#63]
`pdgssvx` will set `info` to be < 0 if there is a problem with one of the arguments, but this is not documented (https://github.com/xiaoyeli/superlu_dist/blob/master/SRC/pdgssvx.c#L491-L498) as it is in SuperLU (https://github.com/xiaoyeli/superlu/blob/master/SRC/sgssvx.c#L337-L352).

I am happy to submit a pull request with this change if appropriate.

**Comment by xiaoyeli** [comment]
I added this line of comment at the 'info' section of the leading comment of p_gssvx().
@joshessman-llnl @pghysels
