### ISSUE TITLE
Compile GPU license in AMD GPU

### ISSUE THREAD

**Issue by Dragon20180618** [xiaoyeli/superlu_dist#65]
In my workspace, only have AMD CPUs, could you give me help by providing the filenames of using cuda.
Now, I am trying to use hip and rocm Open Source to compile SuperLu_dist_6.3.1.
If you have some new idea, I need you help.

**Comment by xiaoyeli** [comment]
In SRC/ directory, do "grep GPU_ACC *.{c,h}", it shows all the files using CUDA.

**Comment by Dragon20180618** [comment]
Thank you very much




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaoyeli/superlu_dist"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月28日(星期三) 中午12:42
收件人:&nbsp;"xiaoyeli/superlu_dist"<superlu_dist@noreply.github.com&gt;;
抄送:&nbsp;"潍坊学院李延龙"<715077252@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xiaoyeli/superlu_dist] Compile GPU license in AMD GPU (#65)





 
In SRC/ directory, do "grep GPU_ACC *.{c,h}", it shows all the files using CUDA.
