### ISSUE TITLE
Superlu_Dist 5.4 Not Always Achieving Machine Precision in Solve

### ISSUE THREAD

**Issue by JustinClough** [xiaoyeli/superlu_dist#67]
I'm using superlu_dist 5.4.0 as a preconditioner to a GMRES iterative solver. In theory, since SLUD is a direct solver, I should reduce my residual to machine precision in one step. This happens the majority of the time, but not always. For some instances, it takes up to 8 iterations to reduce the residual below my solver's tolerance. 

I recorded the number of GMRES iterations needed to solve problems of interest with superlu_dist as a preconditioner over 10,369 cases. Here's a table comparing the number of iterations needed and their percent of the total. 

| N Iterations | % Final    |
|--------------|------|
| 1            | 86.6 |
| 2            | 9.0  |
| 3            | 3.0  |
| 4            | 0.4  |
| 5            | 0.1  |
| 6            | 0.2  |
| 7            | 0.2  |
| 8            | 0.1  |

For the roughly 13% of instances where more than one iteration was needed, I've noticed that the residual tends to hang around 1E-3 or 1E-4 before finally dropping. Here is an example output of iteration number and residual for a case where 8 total iterations were needed:
```
  Iter  0:    1.000000e+00
  Iter  1:    3.308318e-03
  Iter  2:    3.023360e-03
  Iter  3:    2.927900e-03
  Iter  4:    2.852753e-03
  Iter  5:    2.713150e-03
  Iter  6:    2.712711e-03
  Iter  7:    2.756637e-04
  Iter  8:    5.628780e-12
```

For comparison, I solved the same 10,369 linear systems using superlu 4.3 (regular). In all cases GMRES converged in one step. Also, the solution vectors from solving with regular superlu were practically the same as those from superlu_dist. Because of that, I'm not so much concerned about the accuracy of the solves with superlu_dist, more just curious of what would be causing it to take multiple steps.

Has anyone else seen behavior like this before or know what could cause this? 

Let me know if there's any other information about my problem set-up that I can share. Thanks in advance for your help!

**Comment by xiaoyeli** [comment]
Sequential SuperLU uses Gaussian elimination with partial pivoting, while SuperLU_DIST uses static pivoting, which pre-pivots the large entries to the diagonal before elimination. The static pivoting scheme is less stable than partial pivoting. The solver has iterative refinement, usually a few steps are sufficient.  GMRES is a stronger iterative solver than iterative refinement, so could work better with a few iterations.

So the behavior you observed is expected.
