### ISSUE TITLE
Reading the sparse matrix, the b vector and the true values x_true vector

### ISSUE THREAD

**Issue by afrah** [xiaoyeli/superlu_dist#7]
In the examples given , dcreate_matrix.c, reads the the sparse matrix from the input file and generates b and x_true vectors. But if I want to read the b and x-true values from the input file  as Hawell-Boeing format allows that. Do you know how to read b vector and x_true values as well or what functions do that? here is my matrix file possion.rsa

> POSSION DATASET, 3D N  2                                                sym     
            12             1             2             7             6
RSA                        8             8            32             0
(9I3)           (26I3)          (5E15.8)            (5E15.8)            
FGX                        1             0
  1  5  9 13 17 21 25 29 33
  1  2  3  4  1  2  6  7  1  3  5  6  1  4  5  7  3  4  5  8  2  3  6  8  2  4
  7  8  5  6  7  8
 6.00000000E+00-1.00000000E+00-1.00000000E+00-1.00000000E+00-1.00000000E+00
 6.00000000E+00-1.00000000E+00-1.00000000E+00-1.00000000E+00 6.00000000E+00
-1.00000000E+00-1.00000000E+00-1.00000000E+00 6.00000000E+00-1.00000000E+00
-1.00000000E+00-1.00000000E+00-1.00000000E+00 6.00000000E+00-1.00000000E+00
-1.00000000E+00-1.00000000E+00 6.00000000E+00-1.00000000E+00-1.00000000E+00
-1.00000000E+00 6.00000000E+00-1.00000000E+00-1.00000000E+00-1.00000000E+00
-1.00000000E+00 6.00000000E+00
-1.25000000E-01-1.25000000E-01-1.25000000E-01-1.25000000E-01-1.25000000E-01
-1.25000000E-01-1.25000000E-01-1.25000000E-01
-0.00000000E-00-0.00000000E-00-0.00000000E-00-0.00000000E-00-0.00000000E-00
-0.00000000E-00-0.00000000E-00-0.00000000E-00
-4.20000000E-02-4.20000000E-02-4.20000000E-02-4.20000000E-02-4.20000000E-02
-4.20000000E-02-4.20000000E-02-4.20000000E-02

**Comment by xiaoyeli** [comment]
Sherry has replied email sent to superlu_news mailing list.
