### ISSUE TITLE
Generated file SRC/superlu_dist_config.h should be removed from the repository

### ISSUE THREAD

**Issue by adayton1** [xiaoyeli/superlu_dist#72]
Since SRC/superlu_dist_config.h should be generated from SRC/superlu_dist_config.h.in, it should be removed from the repository and added to the .gitignore file.

**Comment by xiaoyeli** [comment]
It's a good suggestion.  However, I am hesitating to do that, because some users still prefer to use old-fashioned way of installation: edit the top level make.inc file, then manually "make", instead of using CMake.  For such users, they need to have superlu_dist_config.h available.

**Comment by adayton1** [comment]
That's fair.
