### ISSUE TITLE
SuperLU CUDA Implementation

### ISSUE THREAD

**Issue by holl-** [xiaoyeli/superlu_dist#76]
Hi, I'm looking into solving sparse linear systems on the GPU. Since CUDA is listed as a feature of the latest releases of SparseLU, I was trying to find the relevenat CUDA code in your project.
I found the files `dsuperlu_gpu.cu`, `zsuperlu_gpu.cu` and `superlu_gpu.cu` but they don't seem to contain the actual solver code.
I don't need any distributed features, only solving sparse linear systems on one or multiple GPUs.
Could you point me to the CUDA implementation?

**Comment by xiaoyeli** [comment]
We only offload part of the computations on GPUs. So the matrices are starting off on CPUs, then both CPUs and GPUs are doing work to solve the same linear system.
The files you found are correct GPU codes, containing CUDA kernels.

**Comment by holl-** [comment]
Okay, thanks!
