### ISSUE TITLE
Calling pzgssvx for symmetric matrix

### ISSUE THREAD

**Issue by chikitkin** [xiaoyeli/superlu_dist#78]
Dear SuperLU community,

I use SuperLU to solve complex-valued linear system with symmetric (not hermitian) matrix. 

I create Supermatrix with
```
   zCreate_CompRowLoc_Matrix_dist(
      A, m_glob, n_glob, nnz_loc, m_loc, fst_row_re, 
      nzval, colind, rowptr, SLU_NR_loc, SLU_Z,  SLU_GE // SLU_SYL
      );
```
and then call 
```
   pzgssvx(options, A, SPstruct, y_complex, locSize, nrhs_, grid,
         LUstruct, SOLVEstruct, berr_, stat, &info);
```
with ```SLU_GE``` it works correct, but when I replace ```SLU_GE```  with ```SLU_SYL``` I ger error:

```{       0,       0}: On entry to pzgssvx, parameter number        2 had an illegal value```

So, something is wrong in Supermatrix.
Could you please point out what I do wrong? May be with ```SLU_SYL``` the CSR structure for the matrix should be different?

Thank you in advance! 

Aleksandr Chikitkin.

**Comment by xiaoyeli** [comment]
The symmetric storage SLU_SYL is not yet supported.  Please use the general format SLU_GE, and include both lower and upper parts of the matrix on input.

**Comment by chikitkin** [comment]
Ok, thank you!
