### ISSUE TITLE
Compiling with CompBLAS

### ISSUE THREAD

**Issue by Adrian-Diaz** [xiaoyeli/superlu_dist#79]
Using  the following script:

export COMBBLAS_ROOT=/mnt/c/CombBLAS
export COMBBLAS_BUILD_DIR=${COMBBLAS_ROOT}/_build
export PARMETIS_ROOT=/mnt/c/ParMETIS
export PARMETIS_BUILD_DIR=${PARMETIS_ROOT}/build/Linux-x86_64
cmake -DCMAKE_INSTALL_PREFIX=/mnt/c/superlu_dist/build \
-DCMAKE_CXX_FLAGS="-std=gnu++14" \
-DTPL_PARMETIS_INCLUDE_DIRS="${PARMETIS_ROOT}/include;${PARMETIS_ROOT}/metis/include" \
-DTPL_PARMETIS_LIBRARIES="${PARMETIS_BUILD_DIR}/libparmetis/libparmetis.a;${PARMETIS_BUILD_DIR}/libmetis/libmetis.a" \
-DTPL_ENABLE_COMBBLASLIB=ON \
-DTPL_COMBBLAS_INCLUDE_DIRS="${COMBBLAS_ROOT}/_install/include;${COMBBLAS_ROOT}/Applications/BipartiteMatchings" \
-DTPL_COMBBLAS_LIBRARIES="${COMBBLAS_ROOT}/_install/lib/libCombBLAS.a" \
..

I always get the attached error for an include file in the CompBLAS library regardless of whether I specify -std=c++14 or leave the default CXX_FLAGS.
[error.txt](https://github.com/xiaoyeli/superlu_dist/files/6812645/error.txt)

**Comment by Adrian-Diaz** [comment]
Changing set(CMAKE_CXX_STANDARD 11) in the base CMakeLists file to set(CMAKE_CXX_STANDARD 14) fixed it.

**Comment by xiaoyeli** [comment]
Glad that you figured it out.
