### ISSUE TITLE
MPI ranks factorization and scaling question

### ISSUE THREAD

**Issue by Adrian-Diaz** [xiaoyeli/superlu_dist#81]
Greetings,

Does SuperLUDist require the number of MPI ranks it runs on to be a power of 2? Also what is the expected algorithmic scaling as a function of the number of rows, N, and the number of MPI ranks, P, when the matrix is banded and sparsely stored? Thanks for any info.

**Comment by xiaoyeli** [comment]
The number of MPI ranks do not need to be power of two.
For general sparse matrices, there is no closed formula regarding FLOPS scaling.
For typical regular 2D discretized PDEs, the sparse factorization scales like N^{3/2}.
For typical regular 3D discretized PDEs, the sparse factorization scales like N^{2}.
