### ISSUE TITLE
Creating releases for several older tags

### ISSUE THREAD

**Issue by zerothi** [xiaoyeli/superlu_dist#86]
It would be really helpful if you could make releases of the following tags. We have some software which has been benchmarked against these versions and testing against different releases in a coherent manner is important for CI's.

Hope you take the time (pressing buttons ;)) to release these:
- [x] https://github.com/xiaoyeli/superlu_dist/releases/tag/v6.4.0
- [x] https://github.com/xiaoyeli/superlu_dist/releases/tag/v6.3.1
- [x] https://github.com/xiaoyeli/superlu_dist/releases/tag/v6.3.0
- [x] https://github.com/xiaoyeli/superlu_dist/releases/tag/v6.2.0
- [x] https://github.com/xiaoyeli/superlu_dist/releases/tag/v6.1.1
- [x] https://github.com/xiaoyeli/superlu_dist/releases/tag/v6.1.0

Also a request for future versions. It is a little difficult to follow the naming conventions, for instance you have https://github.com/xiaoyeli/superlu_dist/releases/tag/v6.4.0-amd which is not a version tag, but rather version + info tag.
It makes it very difficult to parse in CI. A more stringent release version naming convention by only using version numbers would be greatly appreciated. For the v6.4.0-amd release one could rightfully have noted this as v6.4.1 and indicating that amd hip support is enabled.

**Comment by xiaoyeli** [comment]
I made the releases of the older versions.
Thanks for the suggestions. We will keep this in mind for future reference.

cc: @liuyangzhuan
