### ISSUE TITLE
build failure with SLU_HAVE_LAPACK=TRUE

### ISSUE THREAD

**Issue by klindsay28** [xiaoyeli/superlu_dist#89]
I get a build failure with `SLU_HAVE_LAPACK=TRUE` because of line 640 in the following block.
It looks like an extra line from a git merge was accidentally left in.

https://github.com/xiaoyeli/superlu_dist/blob/a0c2dcdaeb206fe3000cd301a297e845d1882cfb/SRC/superlu_ddefs.h#L638-L642

**Comment by xiaoyeli** [comment]
Fixed.

**Comment by klindsay28** [comment]
Thank you for the fix in 5f2281b.
