### ISSUE TITLE
Running Example Errors

### ISSUE THREAD

**Issue by afrah** [xiaoyeli/superlu_dist#9]
I installed Superlu-dist with dependencies with no error but whenn I run the examples , I got this error in almost all examples 

`:~/package/SuperLU_DIST_5.1.3/EXAMPLE$ mpiexec -n 4 ./pddrive -r 2 -c 2 g4.rua
Input matrix file: g4.rua
	Process grid	2 X 2
.. blocking parameters from sp_ienv():
**    relaxation           :       20
**    max supernode        :      128
**    estimated fill ratio :        5
.. options:
**    Fact             :    0
**    Equil            :    1
**    ParSymbFact      :    0
**    ColPerm          :    4
**    RowPerm          :    1
**    ReplaceTinyPivot :    1
**    IterRefine       :    2
**    Trans            :    0
**    num_lookaheads   :   10
**    SymPattern       :    0
**    lookahead_etree  :    0
.. equilibrated? *equed = N
.. LDPERM job        5	 time: 0.00
.. anorm 2.000000e+00
   Current memory used:         416 bytes
   Current memory used:         416 bytes
   Maximum memory used:         416 bytes
***Memory allocation failed for OMETIS: cptr. Requested size: 549755814024 bytes
   Current memory used:         416 bytes
   Maximum memory used:         416 bytes
***Memory allocation failed for OMETIS: cptr. Requested size: 549755814024 bytes
   Current memory used:         416 bytes
   Maximum memory used:         416 bytes
***Memory allocation failed for OMETIS: cptr. Requested size: 549755814024 bytes
   Maximum memory used:         416 bytes
***Memory allocation failed for OMETIS: cptr. Requested size: 549755814024 bytes
.. Use METIS ordering on A'+A

   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
PID 31639 RUNNING AT afrah-TECRA-R950
 EXIT CODE: 139
CLEANING UP REMAINING PROCESSES
 YOU CAN IGNORE THE BELOW CLEANUP MESSAGES

YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Segmentation fault (signal 11)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions

------------------------------------------------------------------------------
This is my makefile.inc

////#//
//#
//#  Program:         SuperLU_DIST
//#
//#  Module:          make.inc
//#
//#  Purpose:         Top-level Definitions
////#
//#  Creation date:   March 1, 2016	version 5.0.0
//#
//#  Modified:	    
//#		    
//#
//#
//#
//#  The name of the libraries to be created/linked to
//#
VERSION		= 5.1.3
SuperLUroot	= ${HOME}/package/SuperLU_DIST_${VERSION}
DSUPERLULIB   	= $(SuperLUroot)/superlu_dist-install/lib/libsuperlu_dist.a

BLASDEF 	= -DUSE_VENDOR_BLAS
BLASLIB   	= -L/home/afrah/package/OpenBLAS-0.2.20/openBLAS-install/lib -lopenblas

PARMETIS_DIR	:= ${HOME}/package/parmetis-4.0.3
I_PARMETIS := -I${PARMETIS_DIR}/parmetis-install/include -I${PARMETIS_DIR}/metis/metis-install/include
METISLIB := -L${PARMETIS_DIR}/metis/metis-install/lib -lmetis
PARMETISLIB := -L${PARMETIS_DIR}/parmetis-install/lib -lparmetis

LIBS		= $(DSUPERLULIB) ${BLASLIB} ${PARMETISLIB} ${METISLIB}

//#
//#  The archiver and the flag(s) to use when building archive (library)
//#  If your system has no ranlib, set RANLIB = echo.
//#
ARCH         = /usr/bin/ar
ARCHFLAGS    = cr
RANLIB       = /usr/bin/ranlib

CC           = /home/afrah/package/mpich-3.2/mpich-install/bin/mpicc
CFLAGS 	     = -DNDEBUG -DAdd_ -DDEBUGlevel=0 -DPRNTlevel=1 -std=c99 -fPIC -g -O0 ${I_PARMETIS}
CFLAGS	     += -I${HOME}/package/mpich-3.2/mpich-install/include
//# CFLAGS       += -D_LONGINT
//# CFLAGS       +=  
NOOPTS       = -O0
FORTRAN	     = /usr/bin/gfortran

LOADER       = $(CC)
LOADOPTS     = //#-Wl,-rpath=${HOME}/package/SuperLU_DIST_${VERSION}/lib -g //# -Wl,-Bdynamic

**Comment by xiaoyeli** [comment]
You need to check your METIS installation. It looks like with SuperLU, you
compiled with 32-bit integer. Check whether you are also using 32-bit
integer with METIS installation.

Sherry Li

**Comment by afrah** [comment]
I compiled metis with 64 by changing this line in metis.h according to their docs
 #define IDXTYPEWIDTH 64//32

I thought that D_LONGINT option of cflag is for that purpose if not how can I compile superlu-dist with 64 bit.

thank you

**Comment by afrah** [comment]
Oh it is commented ... sorry

**Comment by bhourahine** [comment]
I seem to be getting something similar, but using parmetis/metis 4.0.3 built with both IDXTYPEWIDTH (and REALTYPEWIDTH optionally) at 64 in metis.h

$ ./pdtest.sh 
**-- nrhs = 1, process grid = 1 X 1, fill 2, relax 4, max-super 10
   Current memory used:         440 bytes
   Maximum memory used:         440 bytes
***Memory allocation failed for OMETIS: cptr. Requested size: 13743895350408 bytes
**-- nrhs = 1, process grid = 1 X 1, fill 2, relax 4, max-super 20

This is a kubuntu 17.10 machine with openblas and atlas, and the relevant part of the make.in are

I_PARMETIS := -I${PARMETIS_DIR}/include -I${PARMETIS_DIR}/metis/include
METISLIB := -L${PARMETIS_DIR}/build/Linux-x86_64/libmetis -lmetis
PARMETISLIB := -L${PARMETIS_DIR}/build/Linux-x86_64/libparmetis -lparmetis

LIBS = $(DSUPERLULIB) ${BLASLIB} ${PARMETISLIB} ${METISLIB}

CFLAGS = -DNDEBUG -DDEBUGlevel=0 -DPRNTlevel=1 -std=c99 -O0 -DAdd_ $(I_PARMETIS) \
-DUSE_VENDOR_BLAS -fopenmp
NOOPTS = -O0
FORTRAN = /usr/bin/gfortran
CC = /usr/bin/mpicc
LOADER       = $(CC)
LOADOPTS     = -Wl,-rpath, -fopenmp

**Comment by wenbenst** [comment]
> I compiled metis with 64 by changing this line in metis.h according to their docs #define IDXTYPEWIDTH 64//32
> 
> I thought that D_LONGINT option of cflag is for that purpose if not how can I compile superlu-dist with 64 bit.
> 
> thank you

Hello, I would like to know how you solved this problem in the future? Did you reinstall the metis library and set the IDXTYPEWIDTH and REALTYPEWIDTH variables to 32? Looking forward to your reply, thank you

**Comment by afrah** [comment]
Yes, you have to install metis with 32 IDXTYPEWIDTH for the matrix index size. REALTYPEWIDTH variable for data size.
